#setup ssh known_hosts
ssh-keyscan -t rsa n1 > ~/.ssh/known_hosts
ssh-keyscan -t rsa n2 >> ~/.ssh/known_hosts
ssh-keyscan -t rsa n3 >> ~/.ssh/known_hosts
ssh-keyscan -t rsa n4 >> ~/.ssh/known_hosts
ssh-keyscan -t rsa n5 >> ~/.ssh/known_hosts

scp /etc/hosts n1:/etc/hosts
scp /etc/hosts n2:/etc/hosts
scp /etc/hosts n3:/etc/hosts
scp /etc/hosts n4:/etc/hosts
scp /etc/hosts n5:/etc/hosts

echo ""

cat <<EOF 
Welcome to Jepsen on Docker
===========================

This container runs the Jepsen tests in sub-containers.

To run jepsen test:
    lein test 
EOF

cd /jepsen